import type { Metadata } from "next";
import "./globals.css";

import { Geist } from 'next/font/google'

const geist = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={geist.className + ' antialiased text-foreground bg-background'}>
        {children}
      </body>
    </html>
  );
}
